import Head from "next/head";

import GalleryCarousel from "../../components/gallery-carousel/gallery-carousel.component";
import { GalleryDialogContext } from "../../contexts/gallery-dialog.context";
import { useState, useRef, MouseEvent, useContext, useEffect } from "react";

import DeskNav from "../../components/desk-nav/desk-nav.component";

import styles from "./banners.module.css";

import fs from "fs";

type GalleryProps = {
  images: Array<string>;
};

export default function Banners({ images }: GalleryProps) {
  const [imageIndex, setImageIndex] = useState(0);
  const { modalState, setModalState } = useContext(GalleryDialogContext);

  const galleryDialog = useRef<HTMLDialogElement | null>(null);

  useEffect(() => {
    setModalState(false);
  }, []);

  useEffect(() => {
    if (modalState && !galleryDialog.current?.open)
      // if modal is open
      galleryDialog.current?.showModal();
    else {
      galleryDialog.current?.close();
    }
  }, [modalState]);

  function openModal() {
    setModalState(true);
    // galleryDialog.current?.showModal();
  }

  function closeModal() {
    setModalState(false);
    // galleryDialog.current?.close();
  }

  function dialogClickEvent(event: MouseEvent<HTMLDialogElement>) {
    const rect = galleryDialog.current?.getBoundingClientRect();

    const clickedInDialog =
      rect!.top <= event.clientY &&
      event.clientY <= rect!.top + rect!.height &&
      rect!.left <= event.clientX &&
      event.clientX <= rect!.left + rect!.width;

    if (clickedInDialog === false) closeModal();
  }

  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <DeskNav />
      <h1 className={styles.h1}> BANNERS </h1>
      <div>
        {/* {modalIsOpen ? (
          <div className={styles.close_button} onClick={closeModal}>
            &#10006;
          </div>
        ) : (
          ""
        )} */}

        <section className={styles.gallery_section}>
          <div className={`${styles.photo_editing_gallery} ${styles.gallery}`}>
            <div className={styles.gallery_items}>
              {images.map((image, index) => (
                <div
                  className={styles.gallery_item}
                  onClick={() => {
                    setImageIndex(index);
                    openModal();
                  }}
                  key={index}
                >
                  <img src={image} alt="" />
                </div>
              ))}
            </div>
          </div>
        </section>

        <dialog
          ref={galleryDialog}
          className={styles.gallery_dialog}
          onClick={dialogClickEvent}
        >
          <GalleryCarousel images={images} index={imageIndex} />
        </dialog>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const images = fs.readdirSync("public/graphics/banners/");
  const images_ = images.map((image) => `/graphics/banners/${image}`);

  return { props: { images: images_ } };
}
