import Head from "next/head";
import Gallery from "../../components/gallery/gallery.component";
import DeskNav from "../../components/desk-nav/desk-nav.component";

import fs from "fs";

type GalleryProps = {
  images: Array<string>;
};

export default function Banners({ images }: GalleryProps) {
  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <DeskNav />
      <Gallery title="BANNERS" images={images} />
    </>
  );
}

export async function getStaticProps() {
  const images = fs.readdirSync("public/graphics/banners/");
  const images_ = images.map((image) => `/graphics/banners/${image}`);

  return { props: { images: images_ } };
}
