import fs from "fs";

import Head from "next/head";
import DeskNav from "../../components/desk-nav/desk-nav.component";
import Gallery from "../../components/gallery/gallery.component";

type GalleryProps = {
  images: Array<string>;
};

export default function Thumbnails({ images }: GalleryProps) {
  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <DeskNav />
      <Gallery title="THUMBNAILS" images={images} />
    </>
  );
}

export async function getStaticProps() {
  const images = fs.readdirSync("public/graphics/thumbnails/");
  const images_ = images.map((image) => `/graphics/thumbnails/${image}`);

  return { props: { images: images_ } };
}
