import Head from "next/head";
import { Inter } from "@next/font/google";

import DeskNav from "../components/desk-nav/desk-nav.component";
import IntroSection from "../components/intro-section/intro-section.component";
import FooterContacts from "../components/footer-contacts/footer-contacts.component";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AZcreation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DeskNav />
      <IntroSection />
      <FooterContacts />
    </>
  );
}
